public enum TokenType
{
    FUNCTION_TOK, VAR_INPUT_TOK, END_VAR_TOK, BEGIN_TOK, IF_TOK, ELSE_TOK, END_FUNCTION_TOK, THEN_TOK,
    END_IF_TOK, DIGIT_TOK, INT_TOK, VARIABLE_TOK, COLON_TOK, DEFINE_TOK, MULTIPLICATION_TOK, END_EXPRESSION_TOK, LT_EQUAL_TOK
}
